QueryCountClient.php, Test/Html5WebTestCase.php
I'm getting warning "HTML5 Validator service not found at 'http://validator.nu/'" if my html is valid and no messages are returned. So probably you should let empty array pass the test.
=> Empty array of messages means that html is OK

README.md
The current build instructions for the validator are not up to date. I have updated them with according to the latest informations.
Maybe we should also mention in the docs that the `html5validation.url` needs to be explicitely set to e.g. `http://0.0.0.0:8888/` in order to use the validator engine running locally? The default value for `html5validation.url` seems to be `http://validator.nu/`. This means that by default, the HTML5 tests run against the public validator REST API.
=> Add updated validator build instructions

Test/WebTestCase.php
Executed **before** restore fixtures. Required to do something before load the fixtures.
=> WebTestCase: preFixtureRestore() method

Test/Html5WebTestCase.php
the constructor of the Html5WebTestCase does not provide the arguments of the PHPUnit_Framework_TestCase constructor.
That causes issues with features like the data provider
=> fix parent constructor

README.md
The use directive for the schema tool class was missing in the README.md file.
=> add use directive for SchemaTool

README.md
Named fixture references are not only useful for sharing test fixtures between loaders, but can also make tests more easy to read since you can directly refer to items by reference name.
=> Update README.md about using fixture references

README.md
In the README there were a few issues with the referencing fixtures in tests section. I corrected them to what I believe was the intention of the example.
=> Fix LoadMemberAccounts fixture reference in README

README.md
```session.storage.filesystem``` it is an alias for ```session.storage.mock_file```
I think that mock_file it's more clear to understand the testing purposes.
=> More specific for testing (Mock)

EventListener/ExceptionListener.php, ExampleTests/ExampleFunctionalTest.php, README.md, Resources/config/functional_test.xml, Test/ValidationErrorsConstraint.php, Test/WebTestCase.php, Validator/DataCollectingValidator.php, composer.json
When debugging my controllers I often need more information than isSuccessful currently provides. This PR adds a similar method called assertStatusCode which adds extra information. I don't think I can add this functionality to isSuccessful without changing its signature.
* It listens to kernel.exception rather than trying to read the \<title\> element. The title is fine for HTML responses but one of my projects is a JSON API and it displays errors in JSON format. kernel.exception works for both cases.
* It listens to validation errors, so it can display more information when a form submission fails.
With this assertion, a typical form test might contain:
$client->submit($form);
$this->assertStatusCode(302, $client);
$client->followRedirect();
If it fails, it will fail with an error like: …
=> Extra details when a test fails - assertStatusCode

README.md, Test/WebTestCase.php
```loadFixtureFiles``` uses the kernel's `locateResource` method which only takes symfony resource locators; however Alice's ```Fixtures::load``` method takes either resource locators or file paths.
=> Coax loadFixtureFiles to accept real file paths as well as symfony resource locators

Test/WebTestCase.php
We had the same issue as @maxolasersquad described in #171. The proposed fix has been floating around our code base for a while, but I don't know if it will work in every situation. Maybe somebody would like to take a closer look at it.
Credits for the fix go to my colleague RO.
Explanation:
---------------
In the regular (non-STI) case, the EntityManager returns a proxy - the database is not accessed for the proxy creation.
However, if an entity has subclasses (single table inheritance) the find() method is called directly in EntityManager::getReferences. This then accesses the "old" database ($persister->load() in EntityManager::find).
See also the doctrine documentation on STI mapping:
`There is a general performance consideration with Single Table Inheritance:  If the target-entity of …
=> Fix #171 - Copy backup before restoring it

Test/WebTestCase.php
I revert, this : 
$client = static::makeClient(
[
'username' => 'user@example.com',
'password'   => 'test123',
]
);
is exactly what i need, i did not know it exists, sorry
=> Revert auth array_merge params

.scrutinizer.yml, Controller/DefaultController.php, Entity/User.php, Resources/views/Default/admin.html.twig, Test/WebTestCase.php, Tests/App/config.yml, Tests/App/routing.yml, Tests/Test/WebTestCaseTest.php
Added calls to WebTestCase#makeClient(true) and WebTestCase#loginAs(…) (test failing on Symfony 2.3 is skipped)
Added an /admin URL behind an "access_control" rule
Added the "secured_area" firewall
Scrutinizer: added previously ignored files (same as 7fa5d601a331b04c5b1b091d9e35d39a62cf4f5d for PHPUnit)
=> Improved tests:

.scrutinizer.yml, .travis.yml, DataFixtures/ORM/LoadUserData.php, Entity/User.php, Test/WebTestCase.php, Tests/Test/WebTestCaseTest.php
Fix BC break from d002b6d47089500d6c23ef8a40086c43062d3306
Discussion: https://github.com/liip/LiipFunctionalTestBundle/commit/be05aeb72a7f6897dc645bafbed2b6f58cade8b3#diff-f815866dba659cf4e7aebb6fc769c44cL599
Fixed error with User serialization
Added lastest version of Symfony 2.3 in tests
=> Keep Symfony 2.3 Backward compatibility with "security.context" service

Test/Html5WebTestCase.php
ests: Skip tests from Html5WebTestCase if the validator service didn't return JSON content, see #211 and #213
=> Tests: Skip validator tests if the response is invalid

Tests/Test/Html5WebTestCaseFake.php, Tests/Test/Html5WebTestCaseFakeTest.php
Remove skippable tests in order to restore code coverage
The Bundle won't depend on the validator service during tests
=> Tests: HTML validator: use fake data instead of calling the web service

Tests/Test/WebTestCaseTest.php
Expect PHPUnit_Framework_ExpectationFailedException from invalid validation errors array
It will improve code coverage.
=> Tests: Expect exception from PHPUnit when providing invalid errors array

README.md
The documentation now clearly explains the three existent ways to create already logged in clients.
=> #88 login as and logged in make client documentation

DependencyInjection/Compiler/SetTestClientPass.php, QueryCountClient.php, QueryCounter.php, README.md, Resources/config/functional_test.xml, Test/Html5WebTestCase.php, Tests/AppConfig/config.yml, Tests/DependencyInjection/ConfigurationConfigTest.php, Tests/Test/WebTestCaseConfigTest.php, Tests/Test/WebTestCaseTest.php
Parameters with array nodes are not directly accessible,
the parent node must be declared in PHP before accessing the relevant array key
=> Fix bugs with array parameters

DependencyInjection/Compiler/SetTestClientPass.php, DependencyInjection/LiipFunctionalTestExtension.php, QueryCounter.php, Resources/config/functional_test.xml, Test/Html5WebTestCase.php, Test/WebTestCase.php, Tests/DependencyInjection/ConfigurationConfigTest.php, Tests/DependencyInjection/ConfigurationTest.php
Define array nodes in configuration as sub-nodes
instead of defining parent node as an array
Eg.
"liip_functional_test.query.max_query_count"
will be a node instead of setting an array
"liip_functional_test.query" with a "max_query_count" key.
Revert some changes from #236
Use idea from FOSUserBundle:
https://github.com/FriendsOfSymfony/FOSUserBundle/blob/d3fc0f8b24ff94a8b5d5888f2264853819ae707b/DependencyInjection/FOSUserExtension.php#L238
=> Simpler way to define array parameters

Test/WebTestCase.php
The default `getPhpUnitXmlDir` in the `KernelTestCase` of the `FrameworkBundle` is now [hard-bound](https://github.com/symfony/symfony/blob/4555fecf5395386c1b5c6782f4472da13134f27e/src/Symfony/Bundle/FrameworkBundle/Test/KernelTestCase.php#L44) to the name `phpunit`, which blows my fragile behat-driven feature suite.
Overriding `getPhpUnitXmlDir` is the easy solution, but with `self` instead of `static` it cannot be done.
I'm not sure about the performance impact of such a change.
I know I should override the whole `createKernel`, but... but... :dog:
=> Use `static` instead of `self` for late static binding to allow overriding

Command/RunParatestCommand.php, Tests/Command/ParatestCommandTest.php, paratest.md
=> Rename "test:run" to "paratest:run"

Command/RunParatestCommand.php, Tests/AppConfig/config.yml, Tests/Command/ParatestCommandTest.php, Tests/DependencyInjection/ConfigurationConfigTest.php
- New: Pass optional arguments from "paratest:run" to the paratest command
- Define path to PHPUnit in AppConfig/config.yml
- Use runCommand() instead of StreamOutput and BufferedOutput in order to get the output
=> Fix test of the "paratest:run" command:

.gitignore, DependencyInjection/Compiler/OptionalValidatorPass.php, LiipFunctionalTestBundle.php, Tests/AppConfigLeanFramework/AppConfigLeanFrameworkKernel.php, Tests/AppConfigLeanFramework/config.yml, Tests/Test/WebTestCaseConfigLeanFrameworkTest.php, Utils/HttpAssertions.php
Symfony now allows the user to disable the validator component, which
results in the validator service being undefined. This then causes
errors on container compilation as we expected this to always exist.
To fix this add a compiler pass that removes our wrapper around
validator if the validator itself is undefined.
Fixes #288.
=> Handle Symfony disabling the validator component

Test/WebTestCase.php, Tests/Test/WebTestCaseTest.php
Reverts liip/LiipFunctionalTestBundle#310 because this is a BC break (reported in #311).
Fixes #311.
=> Revert "Allow loadFixtures() without arguments"

Test/WebTestCase.php
Backup file param was passed only to `postReferenceSave` and `preReferenceSave` callbacks but not to `preFixtureRestore` and `postFixtureRestore`. Implementors may need this parameter in those callbacks.
=> Adds backup file param even to preFixtureRestore and postFixtureRestore

.travis.yml, composer.json
simple change - also allow `twig/twig` ~2 series..
it is picked up when i switch to php ~7 locally and unit tests are all green
=> also allow twig/twig ~2.0

.travis.yml, README.md, Test/WebTestCase.php, Tests/Test/WebTestCaseTest.php
Add purge mode for to load fixtures from files because need to truncate tables in some situations
and method of load fixture doesn't allow to switch off FOREIGN_KEY_CHECKS.
=> Add purge mode for to load fixtures from files.

.travis.yml, Test/ValidationErrorsConstraint.php, Tests/Command/CommandTest.php, Tests/DependencyInjection/Compiler/SetTestClientPassMockTest.php, Tests/Test/Html5WebTestCaseMockTest.php, Tests/Test/WebTestCaseTest.php, Utils/HttpAssertions.php, composer.json
My final blocker for migrating an app from Symfony 2.6 / PHPUnit 4.6 / PHP 5.4, to Symfony 2.8 / PHPUnit 6.1 / PHP 7.1.
Is this ok for you? Thanks!
=> Added support for PHPUnit 6.1

README.md
This allows to execute PHPUnit from everywhere in the project, not only from the test case class directory.
Fix #309
=> Update the fixtures path in the documentation

composer.json
1.8.0 is already here and as minor version should be BC, it make more sense to have a minor branch alias.
Plus, this will avoid forgotten branch alias updates.
=> Move branch alias to 1.x

Test/WebTestCase.php
The PR fixes a compatibility issue with doctrine-fixtures-bundle. Since version 3.0.2, if I need to use services in my fixture classes, I have to define the fixtures as services and use DI to get the service in the constructor. This causes problems with the "new" call in WebTestCase. The PR tries to load the fixtures class as a service from the container first. This fixes the issue for me.
=> Try to load class as a service from the container first.

.travis.yml
This PR:
- disallows failures with PHP 7.2: it's now stable and released
- stops testing for Symfony 3.3, since it's not an LTS and 3.4 is stable too
- tests for Symfony 3.4 only once
- stops testing for Symfony 4: we're not ready yet!
=> Simplify Travis matrix

Test/WebTestCase.php
Currently the application is instantiated within the command helper method. This doesn't allow any manipulation (and configuration is not given at the moment).
For test cases I want to avoid that the command catches exceptions (e.g. assertion fails in callbacks).
Minimal invasive way (IMHO) is to allow to override Application instantiation.
```
class MyCommand() extends ContainerAwareCommand
{
//...
public function execute()
{
$myService = $this->getContainer()->get('my.service');
$myService->doSomething();
}
}
class MyTestCase extends WebTestCase
{
//...
public function testSomeSpecialCase()
{
$mock = $this->getMockBuilder(MyService::class)
->disableOriginalConstructor()
->setMethods(['doSomething'])
->getMock();
$mock->expects(self::any())
->method('doSomething')
->will( …
```
=> Enable application manipulation for command helper

Resources/config/functional_test.xml, Resources/config/validator.xml
#270 declare services as public ! By default services are private since sf3.4
https://symfony.com/blog/new-in-symfony-3-4-services-are-private-by-default
=> #270 fix non-existent service in SF3.4/4.0

DependencyInjection/LiipFunctionalTestExtension.php, Resources/config/commands.xml
As requested by @lsmith77 in https://github.com/liip/LiipFunctionalTestBundle/pull/357#issuecomment-354165845, I'm redoing the PR using the XML format for service registration.
I've tested this on my own project with SF 3.4, the deprecations are gone.
=> Fix command deprecations with XML

Utils/HttpAssertions.php
*Php version:* 7.1.6
*Phpunit version:* 7.0.0
*LiipFunctionalTestBundle version*: 1.9.2
After update phpunit from 5.5.4 to 7.0.0 my test case ends with fatal error:
*TestCase*:
```php
class RememberPasswordControllerTest extends WebTestCase
{
...
public function testSomeRequest()
{
$client = $this->createClient();
$url = $this->getUrl('remember_password.change_password', [
'checkerId' => '...',
'code' => '...',
]);
$client->request('POST', $url);
$this->assertStatusCode(400, $client);
}
...
}
```
There was an error:
```
TypeError: Argument 3 passed to PHPUnit\Framework\Assert::assertEquals() must be of the type string, null given, called in /var/www/.../vendor/liip/functional-test-bundle/Utils/HttpAssertions.php on line 81
/var/www/.../vendor/liip/functional-test-bundle/Utils/HttpAssertion …
```
=> fixes #387

README.md, composer.json
As discovered in https://github.com/liip/LiipFunctionalTestBundle/pull/388#issuecomment-362587838, we are not compatible with PHPUnit 7, we should declare it in the `composer.json` for the 1.x releases.
The annoying stuff is that the old releases will be missing this info forever. Should we do something else? Add a "known issue" somewhere?
=> Declare conflict with PHPUnit 7

CHANGELOG.md, README.md, UPGRADE-2.0.md, src/Test/WebTestCase.php, tests/App/DataFixtures/ORM/LoadSecondUserData.php, tests/Test/WebTestCaseConfigMysqlTest.php, tests/Test/WebTestCaseConfigPhpcrTest.php
Add an optional parameter that allows to append fixtures.
As we talked on #174 I have implemented a proposal for that feature.
=> add append fixtures feature to loadFixtures method

src/Test/WebTestCase.php, tests/Test/WebTestCaseTest.php
I realize that I forget to add the append feature to SQLite. I've added it to this PR.
=> add append feature for sqlite on load fixtures method

README.md, src/Resources/config/database_tools.xml, src/Services/DatabaseBackup/MongodbDatabaseBackup.php, src/Services/DatabaseBackup/MysqlDatabaseBackup.php, tests/AppConfig/config.yml, tests/DependencyInjection/ConfigurationConfigTest.php
required https://github.com/liip/LiipFunctionalTestBundle/pull/398
=> database cache from 2.x

src/Test/WebTestCase.php
Hello,
I just wanted to share my finding for freeing some memory during tests execution.
On one of my biggest application I'm currently tests refactoring (tests run in local environment):
Before :
- Without cache : `Time: 45.23 seconds, Memory: 236.00MB`
- With cache : `Time: 40.51 seconds, Memory: 216.00MB`
After :
- Without cache : `Time: 42.88 seconds, Memory: 86.00MB`
- With cache : `Time: 32.09 seconds, Memory: 64.00MB`
Edit: time/memory when the PR was on the master branch.
I believe that the time/memory difference depends on the size of the project (container) so you may get smaller or bigger differences on your own projects.
----
The time/memory during this library tests execution seem unchanged (must confirm that with the Travis build).
=> Reset the containers on tearDown

README.md
Set version explicitly, like in https://github.com/liip/LiipFunctionalTestBundle/pull/409
=> [2.x] Add version 2 in “composer require”

README.md
It's required for Symfony 4 and recommended in symfony 3
=> Quote %vars% in config example in README

tests/DependencyInjection/ConfigurationTest.php
Fix error found in last Travis CI build https://travis-ci.org/liip/LiipFunctionalTestBundle/builds/395431946
Error message:
> PHP Fatal error:  Cannot redeclare static Liip\FunctionalTestBundle\Test\WebTestCase::$container as non static Liip\FunctionalTestBundle\Tests\DependencyInjection\ConfigurationTest::$container in /home/travis/build/liip/LiipFunctionalTestBundle/tests/DependencyInjection/ConfigurationTest.php on line 68
=> Fix property declaration that break tests

src/Resources/config/database_tools.xml, src/Services/FixturesLoaderFactory.php
After this comment: https://github.com/liip/LiipFunctionalTestBundle/pull/432#discussion_r202950021
It does not looks like the best way to do it, but all database tools currently requires the `fixtures_loader_factory` service.
=> Make doctrine-fixtures-bundle non mandatory

src/Annotations/QueryCount.php, src/EventListener/ExceptionListener.php, src/Exception/AllowedQueriesExceededException.php, src/QueryCounter.php, src/Services/DatabaseBackup/MongodbDatabaseBackup.php, src/Services/DatabaseBackup/MysqlDatabaseBackup.php, src/Services/DatabaseBackup/SqliteDatabaseBackup.php, src/Services/DatabaseToolCollection.php, src/Services/FixturesLoaderFactory.php, src/Services/SymfonyFixturesLoaderWrapper.php, tests/App/AppKernel.php
Hello
I did not set final on the `Liip\FunctionalTestBundle\Services\DatabaseTools` because we already extends ORM for Sqlite so it feels like user might need it too.
Maybe we should set more class final?
Fixes #380
=> Make some class final

composer.json
Removed "symfony2" occurence in `composer.json`. Added some keywords as well.
=> Rename Symfony2 to Symfony

src/Test/WebTestCase.php
Given that `$success` is typed as bool, I don't see any usefulness in checking if it's a boolean.
=> [2.x] Remove useless check in `WebTestCase::fetchContent`

src/QueryCounter.php
I could not imagine any relevant default value for this, but the configuration set the defaultMaxCount as null. 
Plus line 38 there is already a check for the nullness so... 
Fixes #424.
=> Allow default max query count to be null

src/Utils/HttpAssertions.php
There was only a placeholder for the method and not the class plus they were not in a logical order.
=> Fix typo in HttpAssertions::assertValidationErrors

composer.json
It's a detail but it helps seeing if a package is there or not.
=> Order composer dependencies by name

doc/database.md
Here's an update to the docs based on my experience setting this up to use SQLite on Symfony 4 with a default project-wide `doctrine.yaml` configured to use PostgreSQL.
The correct parameter to set the location of the SQLite file is `path`. I'm setting `url` to override any other values for this setting. If you don't set this to `null` and in your main `doctrine.yaml` file you have it set to a database url, Doctrine will give you a cryptic error. Lastly, `driver` is required.
=> Update docs for Symfony 4 sqlite database setup

src/Test/WebTestCase.php
This BC was introduced but hidden to static analyzers due to this PHPDoc error.
Maybe we should introduce static analysis in 2.0 CI?
=> [2.0] Fix runCommand PHPDoc

.travis.yml
Not sure about adding the same `EXTRA_PACKAGES` as the one with php 7.2.
Maybe a comment should be added on why this is necessary.
=> Add php7.3 in travis tests

src/Validator/DataCollectingValidator.php, tests/App/Controller/DefaultController.php, tests/App/Resources/views/form_with_embed.html.twig, tests/App/routing.yml, tests/Test/WebTestCaseTest.php
Since the validation service is reused (as a "singleton" if you will) throughout the testing process, any validation errors are cleared for each request via the `kernel.request` event.
When an embedded controller is used, a new sub-request is created which will fire off another `kernel.request` event. This clears any form errors _during_ the test, and causes `assertValidationErrors` to fail incorrectly.
By checking if the event is the master request, we can allow embedded controllers.
I'm not sure if this will impact the possible use of forms within a sub-request. I don't know if that's a thing. 🤔
Thank you for the bundle. 😄
=> Fix #273: form validation works with sub-requests

CHANGELOG.md, src/Annotations/DisableDatabaseCache.php, src/Resources/config/database_tools.xml, src/Services/DatabaseToolCollection.php, src/Services/DatabaseTools/AbstractDatabaseTool.php, src/Services/DatabaseTools/ORMDatabaseTool.php, src/Services/DatabaseTools/ORMSqliteDatabaseTool.php, tests/Test/WebTestCaseConfigMysqlCacheDbTest.php, tests/Test/WebTestCaseConfigMysqlTest.php, tests/Test/WebTestCaseConfigTest.php, tests/Test/WebTestCaseTest.php
It's #480 !
I did a little cleanup of some `@IgnoreAnnotation` missing.
=> Add DisableCacheDb annotation

.travis.yml, README.md, Test/ValidationErrorsConstraint.php, Tests/App/AppKernel.php, Tests/Command/CommandTest.php, Tests/DependencyInjection/ConfigurationTest.php, Tests/Test/WebTestCaseConfigMysqlTest.php, Tests/Test/WebTestCaseConfigPhpcrTest.php, Tests/Test/WebTestCaseTest.php, composer.json, phpunit.xml.dist
See #507
The `void` return type is required for compatibility with PHPUnit 7, so PHP 7.1 is required.
=> 1.x: Allow PHPUnit 7, remove PHP 5.6 support

.travis.yml, src/Test/WebTestCase.php, tests/DependencyInjection/ConfigurationTest.php, tests/Test/WebTestCaseConfigLeanFrameworkTest.php, tests/Test/WebTestCaseConfigTest.php, tests/Test/WebTestCaseTest.php
Fixes #509
Changes required : 
1. Add alias for Client <-> KernelBrowser
2. `protected $client` was turned into a static property (replace `$this->client` by `static::$client`)
Extra changes includes :
1. Fixed calls `static::makeClient()` on a non-static method (replace `static::makeClient()` by `$this->makeClient()`)
=> Add compatibility for Symfony 4.3+

UPGRADE-3.0.md
This add a entry when upgrade to 3.x and using a stub with doctrine class, since the factory has been moved around this is needed.
=> minor: add entry about ConnectionFactory in upgade

.travis.yml, src/Test/WebTestCase.php, tests/DependencyInjection/ConfigurationTest.php, tests/Test/WebTestCaseConfigLeanFrameworkTest.php, tests/Test/WebTestCaseConfigTest.php, tests/Test/WebTestCaseTest.php
=> Feature/cherry pick 4.3

src/Test/ValidationErrorsConstraint.php
~On our project, we got an error from PHPStan because we override the `loadFixtureFiles` and the PHPDoc is not in synch with the function declaration.~
Well, after changing the branch to 3.x, there are not that much of missing arguments type ^^
=> Add some missing arguments type in PHPDoc

src/Utils/HttpAssertions.php, tests/Test/WebTestCaseTest.php
I tried it on a project and seems really useful to understand where the problem is.
It's a little verbose but I couldn't find a way to improve it without removing important information.
=> Add stacktrace to the output of assertStatusCode()

UPGRADE-3.0.md
If you copy paste without really thinking about it, it won't work without the leading \
=> The use statement needs a leading \

composer.json
Related to #434, I think that we don't need this hard dependency.
=> [2.x] Remove hard dependency on doctrine/common

src/Test/WebTestCase.php, tests/Command/CommandTest.php
**Is your feature request related to a problem? Please describe.**
I'm writing a test for a command which accepts user input, so need access to configure the `CommandTester` inputs.
**Describe the solution you'd like**
I'd like to be able to easily configure the inputs to the command I am testing.
**Describe alternatives you've considered**
I considered splitting the current `runCommand` into two parts, one for building the command (which would create a `CommandTester` instance and return it, where it could additionally configured by specific tests) and another for running it. This felt awkward though because the configure/run parameters are better viewed in one place.
**Additional context**
Please let me know if there are better ways to approach this that are already supported, I …
=> Command Inputs

composer.json
According to the [Composer's documentation](https://getcomposer.org/doc/articles/aliases.md#branch-alias), it should be `3.x-dev`.
=> Update composer branch-alias to 3.x-dev

tests/Command/CommandTest.php
Hi, just replaced deprecated PHPUnit assert so that tests won't throw warnings.
#SymfonyHackday
=> Replaced deprecated assertContains with assertStringContainsString

doc/logged.md, src/Test/WebTestCase.php, tests/Test/WebTestCaseConfigTest.php
Booting a kernel before calling Symfony WebTestCase::createClient() is deprecated in Symfony 4.4 (symfony/symfony#32056). This exposed an issue with LiipTestFixturesBundle which was causing multiple kernels to be booted during a test. After fixing this in liip/LiipTestFixturesBundle#62 it was brought to my attention that Liip WebTestCase::loginAs is now broken since we require the client to be created before loading fixtures.
As a result, I think deprecating the `loginAs` method and adding a `loginClient` method is the best path forward. Note that in Symfony 5.1 we have  [`$client->loginUser()`](https://symfony.com/blog/new-in-symfony-5-1-simpler-login-in-tests) which is very similar.
I've been using a similar helper function in my projects for a couple of years now, and after suggesting …
=> Create WebTestCase::loginClient to allow working with a single kernel

doc/query.md
need to enable profiling on doctrine bundle too otherwise, the profiler will not record the queries.
=> [Doc] add doctrine profiling part to enable query counter

src/Utils/HttpAssertions.php
Lately in my projects I've been getting this deprecation warning when running tests:
> Since symfony/framework-bundle 5.2: Accessing the "liip_functional_test.validator" service directly from the container is deprecated, use dependency injection instead.
That service has `public="true"` so I'm not sure why this warning happens. Maybe it's some nuance of service decoration.
This can be fixed by going through `test.service_container`.
=> Fix Symfony 5.2 deprecation

src/Test/WebTestCase.php, tests/Command/CommandTest.php
This fix allows to extend `WebTestCase` and override the static `$env` property value effectively.
Closes issue #595
=> Fix access to static $env property  form 'self::$env' to 'static::$env'

.github/workflows/tests.yml, composer.json, tests/App/bootstrap.php
=> allow doctrine/annotations 2

tests/Test/WebTestCaseTest.php
Method `setMethods` on `Response` is deprecated in phpunit 10.x.
=> fix setMethods is deprecated phpunit 10

.github/workflows/tests.yml, CHANGELOG.md, composer.json, tests/Command/CommandTest.php, tests/DependencyInjection/ConfigurationConfigTest.php, tests/DependencyInjection/ConfigurationTest.php
Fix 2 warnings in phpunit 10 (static dataproviders)
=> feat: drop support for php 7.2, 7.3

.github/workflows/tests.yml, composer.json, tests/App/AppKernel.php, tests/App/Entity/User.php, tests/App/config_php8.yml
This may allow Symfony 7 support.
Older version were dropped and older PHP version.
Fell free to comment/annotate 😃 
Fixes #630
=> Symfony 7 compatibillity

doc/basic.md, doc/command.md, src/Test/WebTestCase.php, tests/App/Controller/DefaultController.php, tests/App/Service/DependencyService.php, tests/App/Service/Service.php, tests/App/config.yml, tests/App/routing.yml, tests/Test/WebTestCaseTest.php
Handy helper to mock services in the container when doing command tests.
=> Add helper method to set service mocks in the container.
