liip/LiipFunctionalTestBundle

Test/WebTestCase.php
=> solve Eclipse warnings about unresolvable classes

README.md
=> added more details on how to create already logged client

Test/WebTestCase.php, composer.json
Hi @lsmith77 ,
So here is my code. I added the foreign keys check as we need it on our project with the platform test as you suggest : https://github.com/liip/LiipFunctionalTestBundle/issues/145
=> #143 add loadFixtureFiles with Nelmio alice

Test/WebTestCase.php
=> fixed issue #149 - short array syntax is not available on php 5.3

README.md, Test/WebTestCase.php
This took me quite some time to find: https://github.com/liip/LiipFunctionalTestBundle/issues/143
This will allow users to return their fixtures when calling loadFixtureFiles
=> Improve Alice integration

Test/WebTestCase.php
Parameter passed to "makeClient()" should override the default one in config_test.yml.
=> Fixed auth array_merge params

DependencyInjection/LiipFunctionalTestExtension.php, README.md, Resources/config/functional_test.xml, Resources/config/validator.xml
related to https://github.com/liip/LiipFunctionalTestBundle/issues/177
=> using assertValidationErrors() requires Symfony 2.5+

Test/WebTestCase.php
=> Replace deprecated hardcoded argument with class constant (Fix #200)

Test/WebTestCase.php
fixes #135
due to the minor BC break I guess we should at least bump the minor version
=> cleaned up some of the fixture related code, minor BC break

Controller/DefaultController.php, Tests/Command/CommandTest.php, Tests/Test/WebTestCaseTest.php, phpunit.xml.dist
Added NotBlank constraint to the form
Added different commands calls (improve code coverage)
PHPUnit Code Coverage: added files located at root of the bundle: LiipFunctionalTestBundle.php, QueryCountClient.php and QueryCounter.php
=>  Tests: improved command and form tests

DataFixtures/ORM/user.yml, Tests/Test/WebTestCaseTest.php, composer.json
This will improve code coverage.
=> Tests: Added nelmio/alice

DependencyInjection/Configuration.php, Resources/config/functional_test.xml, Test/Html5WebTestCase.php, Tests/App/config.yml, Tests/Test/Html5WebTestCaseTest.php
This will improve code coverage.
=> Tests: Added HTML5 validation

DataFixtures/ORM/LoadUserData.php, Resources/views/layout.html.twig, Tests/App/config.yml, Tests/Test/WebTestCaseTest.php
Check that the user is logged in when using makeClient(true)
Added a text in Twig in order to display whether the user is logged in
=> Tests: Added several users created from in_memory array

README.md
isSuccessful()
assertStatusCode()
fetchCrawler()
fetchContent()
getURL()
=> Add methods from WebTestCase.php in documentation

Test/WebTestCase.php
Split loadFixtureFiles() functions in 3 distinct functions
=> Refactor loadFixtureFiles() with 2 new functions

README.md
=> README.md: Use HautelookAliceBundle Faker Providers

Tests/App/AppKernel.php, Tests/App/DataFixtures/Faker/Provider/FooProvider.php, Tests/App/DataFixtures/ORM/user_with_custom_provider.yml, Tests/App/config.yml, Tests/Test/WebTestCaseTest.php
=> Test HautelookAliceBundle with Faker Provider

README.md
=> README.md: Add note about clearing cache when cache_sqlite_db is enabled

README.md, Test/WebTestCase.php, Tests/Test/WebTestCaseConfigTest.php
=> Fixes #257: Check all the dependencies when checking database cache

README.md
Missing semicolon in setup config.
=> Fix documentation error.

.scrutinizer.yml, Test/WebTestCase.php, Utils/HttpAssertions.php, phpunit.xml.dist
=> Extract HTTP assertions from Test/WebTestCase

Test/WebTestCase.php
=> Fixes #276: WebTestCase: Pass $omName to cleanDatabase()

fastest.md
Should be "fastest", not "paratest"
=> Change reference to paratest in fastest doc

README.md
`makeClient` is [instance method of WebTesCase](https://github.com/liip/LiipFunctionalTestBundle/blob/master/Test/WebTestCase.php#L691), while in example it is demonstrated as static method.
=> Static vs instance method makeClient in readme

.travis.yml, README.md, Test/WebTestCase.php, Tests/Test/WebTestCaseConfigMysqlTest.php, composer.json
as per issue #289
new pull request, since I messed up the history of the previous branch ;(
=> support 'exclude from purge' feature from doctrine/data-fixtures

Test/WebTestCase.php, Tests/Test/WebTestCaseTest.php
=> Add support for wrong fixture path outside a bundle

README.md
No need to enable bundle in dev
=> Suggest to enable bundle only in test environment

.travis.yml
=> Travis CI: Use Ubuntu Trusty

README.md, Tests/App/config.yml
=> README: Harmonize “session.storage.*” configuration

.travis.yml, Test/WebTestCase.php, Tests/Command/CommandConfigTest.php, Tests/Command/CommandTest.php, Tests/Command/ParatestCommandTest.php, Tests/DependencyInjection/ConfigurationConfigTest.php, Tests/Test/WebTestCaseConfigLeanFrameworkTest.php, Tests/Test/WebTestCaseConfigMysqlTest.php, Tests/Test/WebTestCaseConfigPhpcrTest.php, Tests/Test/WebTestCaseConfigTest.php, composer.json
=> Travis: Support Symfony 3.4 and test PHP 7.2

Command/RunParatestCommand.php, README.md, Test/WebTestCase.php, Tests/Command/CommandTest.php, Tests/Command/ParatestCommandTest.php
=> Drop support of Symfony < 2.7

README.md
=> Add badges and links to packagist

README.md, src/Test/WebTestCase.php, tests/Test/WebTestCaseTest.php
* Allow loading empty fixtures
* Added a test for loadFixtures without parameters
Changes from #310 can be applied on a major release
Fixes #313
=> Allow loadFixtures() without arguments (#310)

src/Resources/config/functional_test.xml, src/Resources/config/validator.xml
I think that we need to port #367 to the 2.x branch.
=> #367 fix non-existent service in SF4.0

CHANGELOG.md, UPGRADE-2.0.md
This starts to add info to the changelog. I watched over the diff between the branches to determine it, but please review it.
I started the upgrade guide, but I'm not sure how to structure it... Suggestions?
=> [2.x] Upgrade guide

composer.json, src/Utils/HttpAssertions.php
=> fixes #387 into 2.x branch

README.md, composer.json
README: Suggest to use the last version
In order to fix an issue I introduced: https://github.com/liip/LiipFunctionalTestBundle/pull/351#issuecomment-350216818
=> [master] Composer: Disallow Symfony 4

README.md
=> [master] Update README to mention 2.x branch

README.md
Add link to documentation updated in #419.
=> README: Add link to 2.x README

tests/Test/WebTestCaseConfigTest.php
The `salt` is generated in `User` constructor, I used this random value in order to check that the backup file was used successfully to stored and retrieve data.
=> Add test for #422

.travis.yml, README.md, UPGRADE-2.0.md, composer.json, tests/Test/WebTestCaseConfigMysqlTest.php
=> Travis CI: Remove MySQL database creation

Test/WebTestCase.php
See #427 for related discussion.
=> Access special test container in getContainer(). Closes #427

composer.json
This is a small normalization of the constraint; it works in the same way.
=> Simplify composer constraint

src/Test/WebTestCase.php
=> [2.0] Use the test container if available

src/Test/WebTestCase.php
=> [2.x] Allow static assert calls

README.md
=> [2.x] Use a session name by default

.github/ISSUE_TEMPLATE/Bug_report.md, .github/ISSUE_TEMPLATE/Feature_request.md
=> added issue templates

CHANGELOG.md, UPGRADE-2.0.md, src/Test/WebTestCase.php, tests/App/Command/TestStatusCodeCommand.php, tests/App/config.yml, tests/Command/CommandConfigTest.php, tests/Command/CommandTest.php
Relates to #329 and #219
I haven't fixed all tests but just one to verify that it's working.
Should I go forward and fix them all? Is this something wanted?
=> Use symfony command tester

.travis.yml, src/Services/DatabaseBackup/AbstractDatabaseBackup.php, src/Services/DatabaseBackup/DatabaseBackupInterface.php, src/Services/DatabaseBackup/MongodbDatabaseBackup.php, src/Services/DatabaseBackup/MysqlDatabaseBackup.php, src/Services/DatabaseBackup/SqliteDatabaseBackup.php, src/Services/DatabaseTools/ORMDatabaseTool.php, tests/AppConfigLeanFramework/AppConfigLeanFrameworkKernel.php, tests/AppConfigMysql/AppConfigMysqlKernel.php, tests/AppConfigMysqlCacheDb/AppConfigMysqlKernelCacheDb.php, tests/AppConfigMysqlCacheDb/config.yml, tests/AppConfigPhpcr/AppConfigPhpcrKernel.php, tests/Test/WebTestCaseConfigMysqlCacheDbTest.php, tests/Test/WebTestCaseConfigMysqlTest.php
=> 2.x: Fix issues with MySQL database backup

UPGRADE-3.0.md
Update after #502
See https://github.com/liip/LiipFunctionalTestBundle/issues/496
=> 3.x: Improve upgrade guide

README.md, doc/caveats.md
=> 2.x add documentation about PHPUnit annotations

CHANGELOG.md, UPGRADE-3.0.md, src/Test/WebTestCase.php, tests/DependencyInjection/Compiler/SetTestClientPassMockTest.php, tests/Test/WebTestCaseConfigTest.php
=> 3.x: extract code from makeClient to 2 new methods

.travis.yml, composer.json, src/DependencyInjection/Compiler/SetTestClientPass.php, src/QueryCountClient.php, src/Test/WebTestCase.php, tests/DependencyInjection/ConfigurationTest.php, tests/Test/WebTestCaseConfigLeanFrameworkTest.php, tests/Test/WebTestCaseConfigTest.php, tests/Test/WebTestCaseTest.php
Revert #512 and cherry-pick from #523 
Replaces #525 
See #520
=> [3.x] Revert add compatibility for symfony 4.3.0 512

.travis.yml, composer.json, src/DependencyInjection/Compiler/SetTestClientPass.php, src/QueryCountClient.php, src/Test/WebTestCase.php, tests/DependencyInjection/Compiler/SetTestClientPassMockTest.php, tests/DependencyInjection/ConfigurationTest.php, tests/Test/WebTestCaseConfigLeanFrameworkTest.php, tests/Test/WebTestCaseConfigTest.php, tests/Test/WebTestCaseTest.php
Backport of #526
Revert #519
Cherry-pick of #522
See #520
=> 2.x revert feature/cherry pick 4.3

src/Test/WebTestCase.php
=> Remove obsolete properties from WebTestCase

composer.json, tests/App/AppKernel.php, tests/Test/WebTestCaseConfigTest.php
=> Composer: remove outdated Doctrine dependencies

tests/App/Command/TestInteractiveCommand.php, tests/App/config.yml, tests/Command/CommandTest.php
=> Add test of command input

composer.json, doc/basic.md, doc/examples.md, src/Test/ValidationErrorsConstraint.php, tests/Command/CommandConfigTest.php, tests/Command/CommandTest.php, tests/Command/ParatestCommandTest.php, tests/Test/WebTestCaseConfigTest.php, tests/Test/WebTestCaseTest.php
=> Allow PHPUnit 8

doc/installation.md
I was installing this and thought that I would add the exact line to the docs to make it more clear which line is being added.
=> Documentation update

composer.json, src/QueryCounter.php, src/Test/ValidationErrorsConstraint.php, src/Test/WebTestCase.php, tests/App/Controller/DefaultController.php
Same as https://github.com/liip/LiipTestFixturesBundle/pull/46
=>  Don't install monolog/monolog 2 for development

.travis.yml, composer.json, src/Command/RunParatestCommand.php, src/EventListener/ExceptionListener.php, src/QueryCountClient.php, src/Test/WebTestCase.php, tests/App/AppKernel.php, tests/App/Command/TestCommand.php, tests/App/Command/TestInteractiveCommand.php, tests/App/Controller/DefaultController.php, tests/App/Resources/views/form.html.twig, tests/App/Resources/views/form_with_embed.html.twig, tests/App/Resources/views/user.html.twig, tests/App/config.yml, tests/Command/ParatestCommandTest.php, tests/Test/WebTestCaseTest.php, tests/Traits/LiipAcmeFixturesTrait.php
Hello,
here are changes to support Symfony 5.
Resolves: #554
Closes: #555
=> Symfony 5 support

composer.json, src/Test/ValidationErrorsConstraint.php
Since #561 is failing, lets try to fix it.
=> Support for PHPUnit 9

.scrutinizer.yml, composer.json
Trying to use twig in version 3 with this project.
=> Update twig to 3

.github/workflows/tests.yml, src/DependencyInjection/LiipFunctionalTestExtension.php, src/Test/ValidationErrorsConstraint.php, src/Test/WebTestCase.php, src/Utils/HttpAssertions.php, tests/App/Command/TestCommand.php, tests/App/Command/TestInteractiveCommand.php, tests/App/Command/TestStatusCodeCommand.php, tests/App/Controller/DefaultController.php
Same as https://github.com/liip/LiipTestFixturesBundle/pull/94
=> Add GitHub actions

.github/workflows/tests.yml, .travis.yml, composer.json
Pretty much just copied liip/LiipTestFixturesBundle#80.
Closes: #575
=> PHP 8 support

.github/workflows/tests.yml, src/Test/WebTestCase.php, tests/Test/WebTestCaseTest.php, tests/Traits/LiipAcmeFixturesTrait.php
=> Fix new static method getContainer in KernelTestCase collision

src/Validator/DataCollectingValidator.php
=> Fix issue with isMainRequest

CHANGELOG.md, src/Test/WebTestCase.php, tests/App/Resources/views/layout.html.twig, tests/App/config.yml, tests/Command/CommandTest.php, tests/Test/WebTestCaseConfigTest.php, tests/Traits/LiipAcmeFixturesTrait.php
=> Added a fix for symfony 5.3 container.

.github/workflows/qa.yml
Same as https://github.com/liip/LiipTestFixturesBundle/pull/191
=> CI: add composer validate

.github/workflows/tests.yml, composer.json
=> composer: move doctrine/annotations to require-dev and suggest

tests/Test/WebTestCaseTest.php
=> PHP-CS-Fixer

doc/query.md
=> doc: add note: Query Counter is not compatible with Symfony 7+

doc/basic.md, doc/logged.md
=> doc: add alternative ways to perform tests

.github/workflows/tests.yml, composer.json
Allow phpunit 11
Also try to add some test cases to the matrix.
=> Add Phpunit 11 support

.github/workflows/tests.yml
=> chore: show PHPUnit version in job name
